package hlju.chaoshang.mapper;

import hlju.chaoshang.po.Applyinfo;
import hlju.chaoshang.po.ApplyinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface ApplyinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbggenerated
     */
    int countByExample(ApplyinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbggenerated
     */
    int deleteByExample(ApplyinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbggenerated
     */
    @Insert({
        "insert into applyinfo (position, name, ",
        "sex, country, province, ",
        "city, ID, passport, ",
        "licenseid)",
        "values (#{position,jdbcType=CHAR}, #{name,jdbcType=CHAR}, ",
        "#{sex,jdbcType=CHAR}, #{country,jdbcType=CHAR}, #{province,jdbcType=CHAR}, ",
        "#{city,jdbcType=CHAR}, #{id,jdbcType=CHAR}, #{passport,jdbcType=VARCHAR}, ",
        "#{licenseid,jdbcType=TINYINT})"
    })
    int insert(Applyinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbggenerated
     */
    int insertSelective(Applyinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbggenerated
     */
    List<Applyinfo> selectByExample(ApplyinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Applyinfo record, @Param("example") ApplyinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applyinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Applyinfo record, @Param("example") ApplyinfoExample example);
}