package hlju.chaoshang.mapper;

import hlju.chaoshang.po.Personalinfo;
import hlju.chaoshang.po.PersonalinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface PersonalinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personalinfo
     *
     * @mbggenerated
     */
    int countByExample(PersonalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personalinfo
     *
     * @mbggenerated
     */
    int deleteByExample(PersonalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personalinfo
     *
     * @mbggenerated
     */
    @Insert({
        "insert into personalinfo (license, openid, ",
        "phoneNum, memberName)",
        "values (#{license,jdbcType=TINYINT}, #{openid,jdbcType=VARCHAR}, ",
        "#{phonenum,jdbcType=CHAR}, #{membername,jdbcType=VARCHAR})"
    })
    int insert(Personalinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personalinfo
     *
     * @mbggenerated
     */
    int insertSelective(Personalinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personalinfo
     *
     * @mbggenerated
     */
    List<Personalinfo> selectByExample(PersonalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personalinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Personalinfo record, @Param("example") PersonalinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personalinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Personalinfo record, @Param("example") PersonalinfoExample example);
}