package hlju.chaoshang.po;

public class Personalinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personalinfo.license
     * 许可证
     * @mbggenerated
     */
    private Byte license;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personalinfo.openid
     * openid
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personalinfo.phoneNum
     * 手机号
     * @mbggenerated
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personalinfo.memberName
     * 会员名
     * @mbggenerated
     */
    private String membername;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personalinfo
     * 获取个人信息对象
     * @mbggenerated
     */
    public Personalinfo(Byte license, String openid, String phonenum, String membername) {
        this.license = license;
        this.openid = openid;
        this.phonenum = phonenum;
        this.membername = membername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personalinfo.license
     *
     * @return the value of personalinfo.license
     * 获取许可证
     * @mbggenerated
     */
    public Byte getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personalinfo.openid
     *
     * @return the value of personalinfo.openid
     * 获取openid
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personalinfo.phoneNum
     * 获取手机号
     * @return the value of personalinfo.phoneNum
     *
     * @mbggenerated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personalinfo.memberName
     * 获取会员名
     * @return the value of personalinfo.memberName
     *
     * @mbggenerated
     */
    public String getMembername() {
        return membername;
    }
}