package hlju.chaoshang.po;

public class Registerinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.phoneNum
     * 手机号
     * @mbggenerated
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.memberName
     * 会员名
     * @mbggenerated
     */
    private String membername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registerinfo.password
     * 密码
     * @mbggenerated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerinfo
     * 获取注册信息对象
     * @mbggenerated
     */
    public Registerinfo(String phonenum, String membername, String password) {
        this.phonenum = phonenum;
        this.membername = membername;
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.phoneNum
     *
     * @return the value of registerinfo.phoneNum
     * 获取手机号
     * @mbggenerated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.memberName
     *
     * @return the value of registerinfo.memberName
     * 获取会员名
     * @mbggenerated
     */
    public String getMembername() {
        return membername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registerinfo.password
     * 获取密码
     * @return the value of registerinfo.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }
}