package hlju.chaoshang.po;

public class Wechat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat.openid
     * openid
     * @mbggenerated
     */
    private String openid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat
     * 获取第三方wechat的信息对象
     * @mbggenerated
     */
    public Wechat(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat.openid
     *
     * @return the value of wechat.openid
     * 获取openid
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }
}